# Authors: Drew Davidson, Zachary Pearson
# Project: EECS 665 Project 1
# Date: 27 August 2020

####### BEGIN DEFINITIONS **********
BINNAME := holycc 
SRCDIR := ./src
INCDIR := ./inc
OBJDIR := ./obj
TESTDIR := ./tests

LEXER_TOOL := flex

HOST_SYS := $(shell uname -s)

CPP_SRCS := $(wildcard $(SRCDIR)/*.cpp) 

OBJ_SRCS := $(OBJDIR)/lexer.o $(CPP_SRCS:$(SRCDIR)/%.cpp=$(OBJDIR)/%.o)

DEPS := $(OBJ_SRCS:.o=.d)

.PHONY: all pre-build rebuild clean test lsp-refs cleantest

####### END DEFINITIONS **********
all: 
	make holycc

clean:
	rm -rf $(OBJDIR) $(SRCDIR)/*.cc $(DEPS) $(BINNAME)

-include $(DEPS)

holycc: pre-build $(OBJ_SRCS)
	$(CXX) -g -std=c++14 -I$(INCDIR) -o $@ $(OBJ_SRCS)

pre-build: 
	@ echo "Attempting to make object directory..."
	- mkdir obj

rebuild: clean all
# Generate compile_commands.json, a file that can be parsed by C++ clients to 
# LSP. Enables jump-to-definition and in-window documentation in Emacs, among
# other things.
lsp-refs:
	bear make 

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp 
	$(CXX) -g -std=c++14 -I$(INCDIR) -MMD -MP -c -o $@ $<

$(SRCDIR)/lexer.yy.cc: $(SRCDIR)/holyc.l
	$(LEXER_TOOL) --outfile=$(SRCDIR)/lexer.yy.cc $<

$(OBJDIR)/lexer.o: $(SRCDIR)/lexer.yy.cc
# TODO: Remove the 'register' keyword from the output of flex
# TODO: Make the sed line cross-platform
# sed -i 's/register//g' $(SRCDIR)/lexer.yy.cc 
	$(CXX) -g -std=c++14 -I$(INCDIR) -c $(SRCDIR)/lexer.yy.cc -o $(OBJDIR)/lexer.o

# TODO: You will need to add to this rule to 
# handle additional test cases
# ---------------------------------------------
test: all
	./holycc $(TESTDIR)/test1.holyc -t $(TESTDIR)/test1.out 2> $(TESTDIR)/test1.err
	diff $(TESTDIR)/test1.out $(TESTDIR)/test1.out.expected
	diff $(TESTDIR)/test1.err $(TESTDIR)/test1.err.expected

# Remove all files automatically generated by make test
# TODO: You will need to add to this rule to clean
# up after additional test cases. 
# ---------------------------------------------
cleantest:
	rm -f test1.out test1.err
	
