name: C/C++ CI

on:
  push:
    branches:
      - main
      - project1
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch
      run: sudo apt-get install flex
    - name: make
      run: make
    - name: make test
      run: make test
