name: C/C++ CI

on:
  push:
    branches:
      - main
      - project1
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: upgrade
      run: sudo apt-get upgrade
    - name: get flex
      run: sudo apt-get install flex
    - name: get flex headers
      run: sudo apt-get install libfl-dev
    - name: make
      run: make
    - name: make test
      run: make test
